radicle-dev/radicle.xyz

Makefile
docs/index.html
docs/styles/style.css
docs/towards-decentralized-code-collaboration.html
pages/index.html.mustache
pages/towards-decentralized-code-collaboration.html.mustache

Towards decentralized code collaboration

---

docs/styles/style.css

Mobile friendliness tweaks

---

pages/towards-decentralized-code-collaboration.html.mustache

intermidary -> intermediary
attraced -> attracted

fixed 2 typos

---

docs/index.html
docs/styles/style.css
pages/index.html.mustache
partials/header.mustache

🎩 Changed the headline to be more magic.
↗️ Moved the external links to be in the top right
🤔 Removed the underline from the logo.

Fix header

---

docs/styles/style.css

fix spacing around the footer

---

docs/docs.html
docs/index.html
docs/styles/forms.css
docs/styles/style.css
docs/styles/typography.css
pages/index.html.mustache
partials/footer.mustache
partials/header.mustache

- Add download button to nav
- Remove line under the headline
- Changed headline to "Secure serverless code collaboration"
- made the one word rainbow-colored by default instead of only on hover
- added all links to footer
- fixed link colors
- added a outline style button

Typography update

---

docs/index.html
docs/styles/style.css
pages/index.html.mustache

Protocols section

---

docs/404.html
docs/downloads.html
docs/index.html
docs/privacy.html
docs/styles/style.css
docs/subscribed.html
docs/terms.html
pages/404.html.mustache
pages/index.html.mustache
partials/head.mustache

- 404 bug
- firefox scaling thing

Cleaning up

---

docs/404.html
docs/downloads.html
docs/index.html
docs/privacy.html
docs/subscribed.html
docs/terms.html
partials/header.mustache

add link to docs in the header nav

---

docs/privacy.html
pages/privacy.html.mustache

- fixed a small error Ange pointed out
- changed the edited date to today

fix copy paste mistake

---

docs/index.html
pages/index.html.mustache

Closes #150 
Signed-off-by: abbey titcomb <abbeytitcomb@gmail.com>

updated matrix community link

---

docs/terms.html
pages/terms.html.mustache

Updated terms according to Ange's feedback.

remove ethereum

---

blog/index.html.mustache
blog/integrating-with-ethereum.html.mustache
docs/blog/index.html
docs/blog/integrating-with-ethereum.html
docs/styles/style.css

add gradients to posts

---

docs/blog/introducing-rad.html

Signed-off-by: Julien Donck <hello@juliendonck.com>

Point to correct sybil governance

---

docs/styles/style.css

Someone pointed out that the titles weren't really readable on mobile, so this adjusts that.

adjust the video top margins so that the titles are more readable on mobile

---

docs/blog/introducing-rad.html

Signed-off-by: Julien Donck <hello@juliendonck.com>

update link contract

---

docs/styles/style.css

Fixes a bug where the ui images were hidden on mobile
Signed-off-by: Julien Donck <hello@juliendonck.com>

fix ui images on mobile

---

blog/introducing-rad.html.mustache
docs/blog/introducing-rad.html

Signed-off-by: Alexander Simmerl <a.simmerl@gmail.com>

Update proposal text

---

blog/introducing-rad.html.mustache
docs/blog/introducing-rad.html

Fixes link that was pointing to localhost.

fix link to point to proposal

---

blog/announcing-the-seeders-program.html.mustache
docs/blog/announcing-the-seeders-program.html

same typo edits from radicle.blog
Signed-off-by: abbey titcomb <abbeytitcomb@gmail.com>

typo edits

---

docs/styles/style.css

fix homepage gif bug

---

README.md

With this merge, the structure of the README file will be improved. This will help future contributors to have a pleasant experience while seeking out information such as **Setting Up the Project**, **Building the Files**.
While we are at the topic of structuring, I propose to create a `.gitattribute` file to prevent diff pollution caused by varying End Of Lines.
Also, why exactly don't you keep a project specific `package.json` file?

Structure README File

---

partials/footer.mustache

- remove mail to link
- replace with link to radicle foundation website

Update Radicle Foundation link in footer

---

pages/index.html.mustache

Linked the community block to the community page

---

docs/index.html
pages/index.html.mustache

With this merge, the position of Purple Square will be updated.
Also, it turns out that the community block updated by 065d802 was not part of the built `index.html`.
- fixes #245

Update Square Position #245

---

blog/index.html.mustache
blog/radicle-orgs.html.mustache
docs/blog/index.html
docs/blog/radicle-orgs.html

Signed-off-by: Julien Donck <hello@juliendonck.com>

Add second author to org post

---

docs/community.html
pages/community.html.mustache

Update Discord link

---

docs/blog/index.html
docs/community.html
docs/index.html
partials/footer.mustache

Fixes link in footer. Closes #286 
Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>

fix link in footer

---

docs/brand.html
docs/community.html
pages/brand.html.mustache
pages/community.html.mustache

When visitors want to join Discord we provide an invite link for the Radicle server. The previous link did not work if you weren’t a member of the server already.

use discord invite link
